### ISSUE TITLE
Allow nesting/hierarchy of route paths

### ISSUE THREAD

**Issue by noahnu** [Brevada/brv#206]
Mainly syntactic sugar.

Current system:

```
routes:
    name1: [ 'GET ^\/level1\/level2\/level3\/?$' ]
    name2: [ 'GET ^\/level1\/level2\/abc\/?$' ]
    name3: [ 'GET ^\/level1\/level2\/def\/ghi\/?$' ]
```

Proposed system:

```
routes:
    route_group_1

route_group_1
    _base: '^\/level1\/level2\/'

    name1: [ 'GET level3\/?$' ]
    name2: [ 'GET abc\/?$' ]
    name3: [ 'GET def\/ghi\/?$' ]
```

With possible extensions for setting default method and middlewares for a group. Names in a group should only be unique for that particular group. Possibly use an alternative rather than "_base"?

NOTE: Routing config is a YAML file, so it must stay valid YAML.
